customhost = "employee22.c9guik6wskvc.us-east-1.rds.amazonaws.com"
customuser = "master_employee"
custompass = "12345678"
customdb = "employee22"
custombucket = "add-employee-4jan"
customregion = "us-east-1"
